-- v6: персональные нормативы простоя (сид из Cars_report.csv, апрель-июль 2026)
CREATE TABLE IF NOT EXISTS client_service_stats (
    client_key  TEXT PRIMARY KEY,
    client_name TEXT NOT NULL,
    visits      INT NOT NULL,
    median_min  NUMERIC(6,1) NOT NULL,
    p80_min     NUMERIC(6,1) NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO client_service_stats VALUES ('НЕМЕЦКО-УКРАИНСКАЯ МЕЖКУЛЬТУРНАЯ ШКОЛА В Г.КИЕВ ЧОУЗ','Немецко-украинская межкультурная школа в г.Киев ЧОУЗ',467,11.5,22.6,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('АГРООБРАЗОВАНИЕ НМЦ ГУ','Агрообразование НМЦ ГУ',63,13.2,26.0,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ СІГМА. УКРАЇНА','ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ  СІГМА. УКРАЇНА',52,14.4,28.4,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('ФРЕНДЛІ ВЕСТ ТОВ','ФРЕНДЛІ ВЕСТ ТОВ',34,21.3,63.9,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('МЕТРО КЕШ ЕНД КЕРІ УКРАЇНА ТОВ','Метро Кеш Енд Кері Україна ТОВ',26,18.0,28.1,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('СТАБІЛІЗЕЙШЕН СУППОРТ СЕРВІСЕЗ БФ БО','СТАБІЛІЗЕЙШЕН СУППОРТ СЕРВІСЕЗ БФ БО',25,15.6,27.5,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('27 ООО','27 ООО',20,14.4,22.4,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('ЛД ІНВЕСТ ТОВ','ЛД ІНВЕСТ ТОВ',19,10.4,15.9,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('ЕПІЦЕНТР К ТОВ','ЕПІЦЕНТР К ТОВ',18,11.7,19.0,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('ЗІНЕКО ТОВ','Зінеко ТОВ',17,17.3,26.7,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('РОШЕН-ЗОДІАК ТОВ','РОШЕН-ЗОДІАК ТОВ',17,9.5,17.0,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('16','16',16,11.3,30.5,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('ЕХОКОР ТОВ','ЕХОКОР ТОВ',15,9.5,15.6,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('РОЗЕТКА УА ТОВ','Розетка УА ТОВ',15,10.5,28.6,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('АРТ ОФ КУКІНГ ТОВ','АРТ ОФ КУКІНГ ТОВ',15,15.7,56.0,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('ШЕВЧЕНКО Т.Г. КНУ ИМ.','Шевченко Т.Г. КНУ им.',15,12.0,15.7,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('ТУПКАЛО ОЛЕКСАНДР ЄВГЕНІЙОВИЧ ФІЗИЧНА ОСОБА ПІДПРИЄМЕЦЬ','ТУПКАЛО ОЛЕКСАНДР ЄВГЕНІЙОВИЧ ФІЗИЧНА ОСОБА ПІДПРИЄМЕЦЬ',14,8.8,11.5,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('УМС МАРИН ТОВ','УМС Марин ТОВ',13,11.2,20.3,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('ГРИФФИН СЕРВИС ООО','Гриффин Сервис ООО',13,11.9,18.0,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('НОВАПЕЙ ТОВ','НоваПей ТОВ',12,11.7,16.6,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('ДАРНИЦЬКИЙ ЗАВОД ЗБК АТ','ДАРНИЦЬКИЙ ЗАВОД ЗБК АТ',11,8.8,12.9,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('ІНТЕРОКО ТОВ','ІНТЕРОКО ТОВ',11,12.5,16.6,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('САНІТА ПРОДАКТ ТОВ','САНІТА ПРОДАКТ ТОВ',9,14.6,32.9,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('МАКСБУД 2020 ТОВ','МАКСБУД 2020 ТОВ',9,16.2,22.0,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('РЫНОК КИЕВ','Рынок Киев',9,12.9,19.0,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('САМИЛОВА ЮЛІЯ ЮРІЇВНА ФОП','Самилова Юлія Юріївна ФОП',9,14.9,24.0,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('ЛЕРУА МЕРЛЕН УКРАЇНА ТОВ','ЛЕРУА МЕРЛЕН УКРАЇНА ТОВ',8,23.3,27.0,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('ФУДСЕРВИС МД ООО','Фудсервис МД ООО',8,12.0,32.1,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('ТЕТА-ПРЕСТИЖ ЧП','ТЕТА-Престиж ЧП',7,9.2,9.8,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('УКРАИНСКИЕ ХИМИЧЕСКИЕ ТЕХНОЛОГИИ ООО','Украинские химические технологии ООО',7,12.9,13.6,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('АРИТЕЙЛ ООО','Аритейл ООО',7,14.2,47.1,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('КЛЕОН-ОЙЛ ТОВ','КЛЕОН-ОЙЛ ТОВ',7,17.6,26.3,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('АТМА ТОВ','АТМА ТОВ',7,10.8,27.7,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('ЗАРУДНИЦКАЯ Л.Ю. ФЛП','Зарудницкая Л.Ю. ФЛП',7,14.3,24.9,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('ТЕМП-2000 ООО','ТЕМП-2000 ООО',7,15.8,18.3,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('КИЕВГОРВТОРРЕСУРСЫ ООО','Киевгорвторресурсы ООО',6,11.4,21.4,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('АПТЕКА ГОРМОНАЛЬНЫХ ПРЕПАРАТОВ ООО','АПТЕКА ГОРМОНАЛЬНЫХ ПРЕПАРАТОВ ООО',6,7.6,8.1,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('УКРАЇНСЬКІ ХІМІЧНІ ТЕХНОЛОГІЇ ЛТД ТОВ','Українські хімічні технології ЛТД ТОВ',6,12.9,13.9,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('ДУ ЦІТ МВС УКРАЇНИ','ДУ ЦІТ МВС УКРАЇНИ',5,17.0,33.1,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('ДНІПРО-М ТОВ','ДНІПРО-М ТОВ',5,15.9,26.8,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('ГАРАНТ СТАТУС ГРУП ТОВ','ГАРАНТ СТАТУС ГРУП ТОВ',5,11.2,17.6,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('ПРЕМІУМ-МАРКЕТ','Преміум-маркет',5,9.8,14.9,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('НОВА ПОШТА ТОВ','Нова пошта ТОВ',5,13.2,14.9,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('ЭДВАНСИС ГРУПП ООО','Эдвансис Групп ООО',5,10.8,15.0,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('ГАРАНТ СТАТУС ГРУП ЛТД ТОВ','ГАРАНТ СТАТУС ГРУП ЛТД ТОВ',5,10.9,75.0,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('ЕКСПАНДІА ТОВ','Експандіа ТОВ',5,16.3,31.4,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('ООО ИНТАЙМ','ООО Интайм',5,11.3,19.2,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
INSERT INTO client_service_stats VALUES ('РIЗНИК Д.А.ФОП','РIЗНИК Д.А.ФОП',5,13.9,41.1,now()) ON CONFLICT (client_key) DO UPDATE SET visits=EXCLUDED.visits, median_min=EXCLUDED.median_min, p80_min=EXCLUDED.p80_min, updated_at=now();
